name: 'test'
on:
  pull_request:
    branch:
      - '**'

# Stop tests running for older commits when a new one is added to the PR.
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  ACCOUNT: ${{ secrets.ACCOUNT }}
  IT_USERNAME: ${{ secrets.IT_USERNAME }}
  IT_PASSWORD: ${{ secrets.IT_PASSWORD }}

jobs:
  lint_test:
    runs-on: ubuntu-latest
    container: node:18.12.1
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create .env file
        run: |
          echo "ACCOUNT=$ACCOUNT" >> .env
          echo "IT_USERNAME=IT_USERNAME" >> .env
          echo "IT_PASSWORD=IT_PASSWORD" >> .env
      - name: 'cache Node modules'
        uses: actions/cache@v3.0.11
        with:
          path: '**/node_modules/'
          key: v1-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-node-${{ hashFiles('**/yarn.lock') }}
            v1-node-
      - name: 'install dependencies'
        run: yarn install --frozen-lockfile --non-interactive
      - name: eslint
        run: 'yarn eslint'
      - name: prettier
        run: yarn prettier:check
      - name: test
        run: yarn test
